/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;
import koneksi.koneksi;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Lenovo
 */
public class formPasien extends javax.swing.JFrame {

    private Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;
    /**
     * Creates new form formPasien
     */
    public formPasien() {
        initComponents();
        dataTable();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPasien = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel_NoIdentitas = new javax.swing.JLabel();
        jTextField_Namapasien = new javax.swing.JTextField();
        jLabel_namaPasien = new javax.swing.JLabel();
        jTextField_NoIdentitas = new javax.swing.JTextField();
        jLabel_jenisKelamin = new javax.swing.JLabel();
        jRadioButton_Laki = new javax.swing.JRadioButton();
        jRadioButton_Perempuan = new javax.swing.JRadioButton();
        jLabel_Alamat = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea_Alamat = new javax.swing.JTextArea();
        jLabel_Goldar = new javax.swing.JLabel();
        jComboBox_Goldar = new javax.swing.JComboBox<>();
        jButton_Save = new javax.swing.JButton();
        jButton_Edit = new javax.swing.JButton();
        jButton_Delete = new javax.swing.JButton();
        jButton_Clear = new javax.swing.JButton();
        jButton_Exit = new javax.swing.JButton();
        jLabel_Katakunci = new javax.swing.JLabel();
        jTextField_katakunci = new javax.swing.JTextField();
        jButton_Cari = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabelPasien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No. Identitas", "Nama Pasien", "Jenis Kelamin", "Alamat", "Golongan Darah"
            }
        ));
        tabelPasien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPasienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelPasien);

        jLabel1.setFont(new java.awt.Font("MS UI Gothic", 1, 56)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("DATA PASIEN");
        jLabel1.setInheritsPopupMenu(false);

        jLabel_NoIdentitas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_NoIdentitas.setText("No. Identitas");

        jTextField_Namapasien.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel_namaPasien.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_namaPasien.setText("Nama Pasien");

        jTextField_NoIdentitas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_NoIdentitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_NoIdentitasActionPerformed(evt);
            }
        });

        jLabel_jenisKelamin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_jenisKelamin.setText("Jenis Kelamin");

        jRadioButton_Laki.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jRadioButton_Laki.setForeground(new java.awt.Color(0, 51, 51));
        jRadioButton_Laki.setText("Laki-laki");

        jRadioButton_Perempuan.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jRadioButton_Perempuan.setText("Perempuan");

        jLabel_Alamat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_Alamat.setText("Alamat - No. Telp");

        jTextArea_Alamat.setColumns(20);
        jTextArea_Alamat.setRows(5);
        jScrollPane3.setViewportView(jTextArea_Alamat);

        jLabel_Goldar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_Goldar.setText("Golongan Darah");

        jComboBox_Goldar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox_Goldar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "AB", "O" }));

        jButton_Save.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Save.setText("SAVE");
        jButton_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SaveActionPerformed(evt);
            }
        });

        jButton_Edit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Edit.setText("EDIT");
        jButton_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EditActionPerformed(evt);
            }
        });

        jButton_Delete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Delete.setText("DELETE");
        jButton_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DeleteActionPerformed(evt);
            }
        });

        jButton_Clear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Clear.setText("CLEAR");
        jButton_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ClearActionPerformed(evt);
            }
        });

        jButton_Exit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Exit.setText("EXIT");
        jButton_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ExitActionPerformed(evt);
            }
        });

        jLabel_Katakunci.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_Katakunci.setText("Kata kunci pencarian");

        jTextField_katakunci.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_katakunci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_katakunciActionPerformed(evt);
            }
        });

        jButton_Cari.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_Cari.setText("Cari");
        jButton_Cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1070, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1019, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_namaPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_NoIdentitas, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_jenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_Alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_Goldar, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton_Save, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(38, 38, 38)
                                        .addComponent(jButton_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(jButton_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(36, 36, 36)
                                        .addComponent(jButton_Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextField_NoIdentitas, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField_Namapasien)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jRadioButton_Laki, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(56, 56, 56)
                                            .addComponent(jRadioButton_Perempuan))
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 725, Short.MAX_VALUE)
                                        .addComponent(jComboBox_Goldar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel_Katakunci, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField_katakunci, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(54, 54, 54)
                                        .addComponent(jButton_Cari, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_NoIdentitas, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_NoIdentitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_namaPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Namapasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_jenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton_Laki)
                    .addComponent(jRadioButton_Perempuan))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel_Alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Goldar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_Goldar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Save)
                    .addComponent(jButton_Edit)
                    .addComponent(jButton_Delete)
                    .addComponent(jButton_Clear)
                    .addComponent(jButton_Exit))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Katakunci)
                    .addComponent(jTextField_katakunci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Cari))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SaveActionPerformed
        // TODO add your handling code here:
        
        String sql = "insert into pasien values (?,?,?,?,?)";
        try{
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1,jTextField_NoIdentitas.getText());
            stat.setString(2,jTextField_Namapasien.getText());
            
            String jenisKelamin = "";
            if(jRadioButton_Laki.isSelected())
            jenisKelamin = "Laki-laki";
            else jenisKelamin = "Perempuan";
            stat.setString(3, jenisKelamin);
            
            stat.setString(4, jTextArea_Alamat.getText());
            stat.setString(5, jComboBox_Goldar.getSelectedItem().toString());
            
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
            
            kosong();
            jTextField_NoIdentitas.requestFocus();
            dataTable();
        } catch (SQLException e){
            JOptionPane.showMessageDialog(null, "Data Gagal disimpan " + e);
            
        }
    }//GEN-LAST:event_jButton_SaveActionPerformed

    private void tabelPasienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPasienMouseClicked
        // TODO add your handling code here:
        
        int bar = tabelPasien.getSelectedRow();
        String a = tabmode.getValueAt(bar, 0).toString();
        String b = tabmode.getValueAt(bar, 1).toString();
        String c = tabmode.getValueAt(bar, 2).toString();
        String d = tabmode.getValueAt(bar, 3).toString();
        String e = tabmode.getValueAt(bar, 4).toString();
       
    jTextField_NoIdentitas.setText(a);
    jTextField_Namapasien.setText(b);
    
    if(c.equals("Laki-laki")) {
        jRadioButton_Laki.setSelected(true);
        jRadioButton_Perempuan.setSelected(false);
    } else {
        jRadioButton_Laki.setSelected(false);
        jRadioButton_Perempuan.setSelected(true);
    };
    
    jTextArea_Alamat.setText(d);
    jComboBox_Goldar.setSelectedItem(e);
    }//GEN-LAST:event_tabelPasienMouseClicked

    private void jButton_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EditActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "update pasien set nama=?, jk=?, alamat=?, goldar=? where id =?";
            PreparedStatement stat = conn.prepareStatement(sql);
            
           
            stat.setString(1,jTextField_Namapasien.getText());
            //stat.SetString(1,jTextField_NoIdentitas.getText());
            String jenisKelamin = "";
            if(jRadioButton_Laki.isSelected()) jenisKelamin = "Laki-laki";
            else jenisKelamin = "Perempuan";
            stat.setString(2, jenisKelamin);
            
            stat.setString(3, jTextArea_Alamat.getText());
            stat.setString(4, jComboBox_Goldar.getSelectedItem().toString());
            stat.setString(5, jTextField_NoIdentitas.getText());
            
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil diubah");
            kosong();
            jTextField_NoIdentitas.requestFocus();
            dataTable();
            
        } catch (SQLException e){
            JOptionPane.showMessageDialog(null, "Data Gagal diubah" +e);
        }
    }//GEN-LAST:event_jButton_EditActionPerformed

    private void jButton_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DeleteActionPerformed
        // TODO add your handling code here:
        
        int ok = JOptionPane.showConfirmDialog(null, "Hapus","Konfirmasi Dialog", JOptionPane.YES_NO_CANCEL_OPTION);
        if(ok == 0){

            try {
                String sql = "delete from pasien where id ='" + jTextField_NoIdentitas.getText()+"'";
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "data berhasil dihapus");
                kosong();
                jLabel_NoIdentitas.requestFocus();
                dataTable();
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, "Data gagal dihapus" + e);
            }
        }
    }//GEN-LAST:event_jButton_DeleteActionPerformed

    private void jButton_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ExitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton_ExitActionPerformed

    private void jButton_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ClearActionPerformed
        // TODO add your handling code here:
        kosong();
        dataTable();
    }//GEN-LAST:event_jButton_ClearActionPerformed

    private void jTextField_katakunciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_katakunciActionPerformed
        // TODO add your handling code here:
        Object[] Baris = {"No identitas", "Nama Pasien", "Jenis Kelamin","Alamat", "Golongan Darah"};
        tabmode = new DefaultTableModel(null, Baris);
        tabelPasien.setModel(tabmode);
        String sql = "Select * from pasien where nama like '%" + jTextField_katakunci.getText()+ "%'";
        try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                
                String a = hasil.getString("id");
                String b = hasil.getString("nama");
                String c = hasil.getString("jk");
                String d = hasil.getString("alamat");
                String e = hasil.getString("goldar");
            
                String[] data = {a,b,c,d,e};
                tabmode.addRow(data);
            }
        } catch (Exception e){
            
       }
       
    }//GEN-LAST:event_jTextField_katakunciActionPerformed

    private void jButton_CariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_CariActionPerformed

    private void jTextField_NoIdentitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_NoIdentitasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_NoIdentitasActionPerformed

    /**
     * @param args the command line arguments
     */
    
    protected void aktif(){
    jTextField_NoIdentitas.setEnabled(true);
    jTextField_Namapasien.setEnabled(true);
    jTextArea_Alamat.setEnabled(true);
    jTextField_NoIdentitas.requestFocus();
    
    }
    protected void kosong(){
      
    jTextField_NoIdentitas.setText("");
    jTextField_Namapasien.setText("");
    jTextArea_Alamat.setText("");
    jRadioButton_Laki.setSelected(true);
    jComboBox_Goldar.setSelectedIndex(0);
    jTextField_katakunci.setText("");
    
    }
    
    protected void dataTable(){
        Object[] baris = {"No Identitas","Nama Pasien","Jenis Kelamin","Alamat","Golongan Darah"};
        tabmode = new DefaultTableModel(null, baris);
        tabelPasien.setModel(tabmode);
        String sql = "Select * from pasien";
        try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                String a = hasil.getString("id");
                String b = hasil.getString("nama");
                String c = hasil.getString("jk");
                String d = hasil.getString("alamat");
                String e = hasil.getString("goldar");
                String [] data = {a,b,c,d,e};
                tabmode.addRow(data);
            }
        }catch (Exception e){
            
        }
        
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formPasien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Cari;
    private javax.swing.JButton jButton_Clear;
    private javax.swing.JButton jButton_Delete;
    private javax.swing.JButton jButton_Edit;
    private javax.swing.JButton jButton_Exit;
    private javax.swing.JButton jButton_Save;
    private javax.swing.JComboBox<String> jComboBox_Goldar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_Alamat;
    private javax.swing.JLabel jLabel_Goldar;
    private javax.swing.JLabel jLabel_Katakunci;
    private javax.swing.JLabel jLabel_NoIdentitas;
    private javax.swing.JLabel jLabel_jenisKelamin;
    private javax.swing.JLabel jLabel_namaPasien;
    private javax.swing.JRadioButton jRadioButton_Laki;
    private javax.swing.JRadioButton jRadioButton_Perempuan;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea_Alamat;
    private javax.swing.JTextField jTextField_Namapasien;
    private javax.swing.JTextField jTextField_NoIdentitas;
    private javax.swing.JTextField jTextField_katakunci;
    private javax.swing.JTable tabelPasien;
    // End of variables declaration//GEN-END:variables
}
