/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;
import koneksi.koneksi;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
/**
 *
 * @author Lenovo
 */
public class formRekamMedis extends javax.swing.JFrame {
    
    private Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;
    /**
     * Creates new form formRekamMedis
     */
    public formRekamMedis() {
        initComponents();
        dataTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField_no_pendaftaran = new javax.swing.JTextField();
        jTextField_id_dokter = new javax.swing.JTextField();
        jTextField_nama_dokter = new javax.swing.JTextField();
        jTextField_no_identitas_pasien = new javax.swing.JTextField();
        jTextField_nama_pasien = new javax.swing.JTextField();
        jTextField_golongan_darah = new javax.swing.JTextField();
        jTextField_tinggi_badan = new javax.swing.JTextField();
        jTextField_berat_badan = new javax.swing.JTextField();
        btn_cari_id_dokter = new javax.swing.JButton();
        btn_no_identitas_pasien = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_diagnosa_dokter = new javax.swing.JTextArea();
        jTextField_tanggal_pemeriksaan = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jTextField_cari_data_riwayat_pasien = new javax.swing.JTextField();
        btn_cari = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btn_save = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();
        btn_edit = new java.awt.Button();
        btn_delete = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel_riwayat_pasien = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1191, 817));

        jLabel1.setFont(new java.awt.Font("MS UI Gothic", 1, 56)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setText("REKAM MEDIS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 766, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("No. Pendaftaran");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("ID Dokter");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Nama Dokter");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("No. Identitas Pasien");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Nama Pasien");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Golongan Darah");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Tinggi Badan");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Berat Badan");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Diagnosa Dokter");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Tanggal Pemeriksaan");

        jTextField_no_pendaftaran.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jTextField_id_dokter.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jTextField_nama_dokter.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jTextField_no_identitas_pasien.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField_no_identitas_pasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_no_identitas_pasienActionPerformed(evt);
            }
        });

        jTextField_nama_pasien.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField_nama_pasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_nama_pasienActionPerformed(evt);
            }
        });

        jTextField_golongan_darah.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField_golongan_darah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_golongan_darahActionPerformed(evt);
            }
        });

        jTextField_tinggi_badan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField_tinggi_badan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_tinggi_badanActionPerformed(evt);
            }
        });

        jTextField_berat_badan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField_berat_badan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_berat_badanActionPerformed(evt);
            }
        });

        btn_cari_id_dokter.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_cari_id_dokter.setText("Cari");
        btn_cari_id_dokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cari_id_dokterActionPerformed(evt);
            }
        });

        btn_no_identitas_pasien.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_no_identitas_pasien.setText("Cari");
        btn_no_identitas_pasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_no_identitas_pasienActionPerformed(evt);
            }
        });

        jTextArea_diagnosa_dokter.setColumns(20);
        jTextArea_diagnosa_dokter.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextArea_diagnosa_dokter.setRows(5);
        jScrollPane1.setViewportView(jTextArea_diagnosa_dokter);

        jTextField_tanggal_pemeriksaan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Cari Data Riwayat Pasien");

        jTextField_cari_data_riwayat_pasien.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField_cari_data_riwayat_pasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_cari_data_riwayat_pasienActionPerformed(evt);
            }
        });

        btn_cari.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_cari.setText("Cari");
        btn_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 208, Short.MAX_VALUE)
                .addComponent(jTextField_cari_data_riwayat_pasien, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField_cari_data_riwayat_pasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cari))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        btn_save.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_save.setText("SAVE");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        btn_clear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_clear.setText("CLEAR");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        btn_exit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_exit.setText("EXIT");
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });

        btn_edit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_edit.setLabel("EDIT");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        btn_delete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_delete.setText("DELETE");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(306, Short.MAX_VALUE)
                .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(256, 256, 256))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_save)
                        .addComponent(btn_delete))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_clear)
                        .addComponent(btn_exit)))
                .addGap(32, 32, 32))
        );

        tabel_riwayat_pasien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tabel_riwayat_pasien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_riwayat_pasienMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabel_riwayat_pasien);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField_no_pendaftaran, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel11)
                                .addGap(28, 28, 28)
                                .addComponent(jTextField_tanggal_pemeriksaan, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField_nama_dokter, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jTextField_id_dokter, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btn_cari_id_dokter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jTextField_no_identitas_pasien, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btn_no_identitas_pasien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jTextField_nama_pasien, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField_golongan_darah, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField_tinggi_badan, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField_berat_badan, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(72, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1050, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel11)
                    .addComponent(jTextField_no_pendaftaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_tanggal_pemeriksaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_id_dokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cari_id_dokter))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField_nama_dokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField_no_identitas_pasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_no_identitas_pasien))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jTextField_nama_pasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jTextField_golongan_darah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jTextField_tinggi_badan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField_berat_badan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_no_identitas_pasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_no_identitas_pasienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_no_identitas_pasienActionPerformed

    private void jTextField_nama_pasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_nama_pasienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_nama_pasienActionPerformed

    private void jTextField_golongan_darahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_golongan_darahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_golongan_darahActionPerformed

    private void jTextField_tinggi_badanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_tinggi_badanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_tinggi_badanActionPerformed

    private void jTextField_berat_badanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_berat_badanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_berat_badanActionPerformed

    private void jTextField_cari_data_riwayat_pasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_cari_data_riwayat_pasienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_cari_data_riwayat_pasienActionPerformed

    private void btn_cari_id_dokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cari_id_dokterActionPerformed
        // TODO add your handling code here:
        String sql = "Select * from dokter where id = '" + jTextField_id_dokter.getText()+"'";
        try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
               String nama = hasil.getString("nama");
               jTextField_nama_dokter.setText(nama);
               jTextField_nama_dokter.setEnabled(false);
        }
            }catch(Exception e){
        }
    }//GEN-LAST:event_btn_cari_id_dokterActionPerformed

    private void btn_no_identitas_pasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_no_identitas_pasienActionPerformed
        // TODO add your handling code here:
        
        String sql = "Select * from dokter where id = '"+ jTextField_no_identitas_pasien.getText()+"'";
        try{        
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                String a = hasil.getString("nama");
                String b = hasil.getString("Golongan Darah");
                
                jTextField_nama_pasien.setText(a);
                jTextField_golongan_darah.setText(b);
                
                jTextField_nama_pasien.setEnabled(false);
                jTextField_golongan_darah.setEnabled(false);
            }
         }catch(Exception e){
        }
    }//GEN-LAST:event_btn_no_identitas_pasienActionPerformed

    private void tabel_riwayat_pasienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_riwayat_pasienMouseClicked
        // TODO add your handling code here:
        
        int bar = tabel_riwayat_pasien.getSelectedRow();
        String a = tabmode.getValueAt(bar, 0).toString();
        String b = tabmode.getValueAt(bar, 1).toString();
        String c = tabmode.getValueAt(bar, 2).toString();
        String d = tabmode.getValueAt(bar, 3).toString();
        String e = tabmode.getValueAt(bar, 4).toString();
        String f = tabmode.getValueAt(bar, 5).toString();
        String g = tabmode.getValueAt(bar, 6).toString();
        String h = tabmode.getValueAt(bar, 7).toString();
        String i = tabmode.getValueAt(bar, 8).toString();
        String j = tabmode.getValueAt(bar, 9).toString();
        
        jTextField_no_pendaftaran.setText(a);
        jTextField_id_dokter.setText(b);
        jTextField_nama_dokter.setText(c);
        jTextField_no_identitas_pasien.setText(d);
            jTextField_nama_pasien.setText(e);
            jTextField_golongan_darah.setText(f);
            jTextField_tinggi_badan.setText(g);
            jTextField_berat_badan.setText(h);
            jTextArea_diagnosa_dokter.setText(i);
            jTextField_tanggal_pemeriksaan.setText(j);
    }//GEN-LAST:event_tabel_riwayat_pasienMouseClicked

    private void btn_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cariActionPerformed
        // TODO add your handling code here:
        Object [] Baris = {"No Identitas", "NamaPasien", "Jenis Kelamin", "Alamat","Golongan Darah"};
        tabmode = new DefaultTableModel(null, Baris);
        tabel_riwayat_pasien.setModel(tabmode);
        String sql = "Select * from dokter where nama like '%" + btn_cari.getText()+"%'";
        try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()){
                String a = hasil.getString("id");
                String b = hasil.getString("nama");
                String c = hasil.getString("jk");
                String d = hasil.getString("alamat");
                String e = hasil.getString("goldar");
            
                String[] data = {a,b,c,d,e};
                tabmode.addRow(data);
            }
        } catch(Exception e){
        }
    }//GEN-LAST:event_btn_cariActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        // TODO add your handling code here:
        String sql = "insert into dokter values (?,?,?,?,?,?,?,?,?,?)";
        try {
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1,jTextField_no_pendaftaran.getText());
            stat.setString(2,jTextField_id_dokter.getText());
            stat.setString(3,jTextField_nama_dokter.getText());
            stat.setString(4,jTextField_no_identitas_pasien.getText());
            stat.setString(5,jTextField_nama_pasien.getText());
            stat.setString(6,jTextField_golongan_darah.getText());
            stat.setString(7,jTextField_tinggi_badan.getText());
            stat.setString(8,jTextField_berat_badan.getText());
            stat.setString(9,jTextArea_diagnosa_dokter.getText());
            stat.setString(10,jTextField_tanggal_pemeriksaan.getText());
            
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil Disimpan");
            kosong();
            jTextField_no_pendaftaran.requestFocus();
            dataTable();
          } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Data Gagal Disimpan" + e);
        }
    }//GEN-LAST:event_btn_saveActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "Update dokter set id_dokter=?, nama_dokter=?, no_identitas_pasien=?, nama_pasien=?, golongan_darah=?, tinggi_badan=?, "
                    + "berat_badan=?, diagnosa_dokter=?, tgl_pemeriksaan=? where no_pendaftaran=?";
     
             PreparedStatement stat = conn.prepareStatement(sql);
            //stat.setString(1,jTextField_no_pendaftaran.getText());
            stat.setString(1,jTextField_id_dokter.getText());
            stat.setString(2,jTextField_nama_dokter.getText());
            stat.setString(3,jTextField_no_identitas_pasien.getText());
            stat.setString(4,jTextField_nama_pasien.getText());
            stat.setString(5,jTextField_golongan_darah.getText());
            stat.setString(6,jTextField_tinggi_badan.getText());
            stat.setString(7,jTextField_berat_badan.getText());
            stat.setString(8,jTextArea_diagnosa_dokter.getText());
            stat.setString(9,jTextField_tanggal_pemeriksaan.getText());
            stat.setString(10,jTextField_no_pendaftaran.getText());
            
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil diubah ");
            kosong();
            jTextField_id_dokter.requestFocus();
            dataTable();
                    
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Data gagal diubah" + e);
        }
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:

        int ok = JOptionPane.showConfirmDialog(null, "Hapus","Konfirmasi Dialog", JOptionPane.YES_NO_CANCEL_OPTION);
        if(ok == 0){

            try {
                String sql = "delete from dokter where no_pendaftaran ='" + jTextField_no_pendaftaran.getText()+"'";
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "data berhasil dihapus");
                kosong();
                jTextField_no_pendaftaran.requestFocus();
                dataTable();
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, "Data gagal dihapus" + e);
            }
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // TODO add your handling code here:
        kosong();
        dataTable();
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btn_exitActionPerformed

    protected void aktif(){
        jTextField_no_pendaftaran.setEnabled(true);
        jTextField_id_dokter.setEnabled(true);
        jTextField_nama_dokter.setEnabled(true);
        jTextField_no_pendaftaran.requestFocus();
    }
    protected void kosong(){
        jTextField_no_pendaftaran.setText("");
        jTextField_id_dokter.setText("");
        jTextField_nama_dokter.setText("");
        jTextField_no_identitas_pasien.setText("");
        jTextField_nama_pasien.setText("");
        jTextField_golongan_darah.setText("");
        jTextField_tinggi_badan.setText("");
        jTextField_berat_badan.setText("");
        jTextArea_diagnosa_dokter.setText("");
        jTextField_tanggal_pemeriksaan.setText("");
    }
     protected void dataTable(){
        Object[] baris = {"No Pendaftaran","ID Dokter","Nama Dokter","No Identitas Pasien","Nama Pasien","Golongan Darah",
        "Tinggi Badan","Berat Badan","Area Diagnosa Dokter","Tanggal Pemeriksaan"};
        
        tabmode = new DefaultTableModel(null, baris);
        tabel_riwayat_pasien.setModel(tabmode);
        String sql = "Select * from dokter";
        try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                String a = hasil.getString("no_pendaftaran");
                String b = hasil.getString("id_dokter");
                String c = hasil.getString("nama_dokter");
                String d = hasil.getString("no_identitas_pasien");
                String e = hasil.getString("nama_pasien");
                String f = hasil.getString("golongan_darah");
                String g = hasil.getString("tinggi_badan");
                String h = hasil.getString("berat_badan");
                String i = hasil.getString("diagnosa_dokter");
                String j = hasil.getString("tgl_pemeriksaan");
                
                String [] data = {a,b,c,d,e,f,g,h,i,j};
                tabmode.addRow(data);
            }
        }catch (Exception e){
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formRekamMedis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formRekamMedis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formRekamMedis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formRekamMedis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formRekamMedis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cari;
    private javax.swing.JButton btn_cari_id_dokter;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_delete;
    private java.awt.Button btn_edit;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_no_identitas_pasien;
    private javax.swing.JButton btn_save;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea_diagnosa_dokter;
    private javax.swing.JTextField jTextField_berat_badan;
    private javax.swing.JTextField jTextField_cari_data_riwayat_pasien;
    private javax.swing.JTextField jTextField_golongan_darah;
    private javax.swing.JTextField jTextField_id_dokter;
    private javax.swing.JTextField jTextField_nama_dokter;
    private javax.swing.JTextField jTextField_nama_pasien;
    private javax.swing.JTextField jTextField_no_identitas_pasien;
    private javax.swing.JTextField jTextField_no_pendaftaran;
    private javax.swing.JTextField jTextField_tanggal_pemeriksaan;
    private javax.swing.JTextField jTextField_tinggi_badan;
    private javax.swing.JTable tabel_riwayat_pasien;
    // End of variables declaration//GEN-END:variables
}
